### ISSUE TITLE
Issue in accessing ffmpeg layer in deploying largefile example

### ISSUE THREAD

**Issue by sivarajendranaidu** [aws-samples/aws-lambda-efs-samples#1]
Tried to create lambda layer using link https://www.serverless.com/blog/publish-aws-lambda-layers-serverless-framework
Update the ProcessFileFunction Layer ARN with the one deployed in the region.
I was able to successfully deploy and running the API endpoint I having issue of with running ffmpeg and getting the following error.
```
2020-07-10T19:40:09.107Z	2d413619-080d-4f21-90cd-271ae8b06726	INFO	Error:  Error: Command failed: /opt/bin/ffmpeg -loglevel error -i /mnt/efs/video.MP4 -s 240x135 -vf fps=1 /mnt/efs/%d.jpg
/bin/sh: /opt/bin/ffmpeg: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: '/opt/bin/ffmpeg -loglevel error -i /mnt/efs/video.MP4 -s 240x135 -vf fps=1 /mnt/efs/%d.jpg'
}
```

**Comment by jbesw** [comment]
I would recommend taking a look at the ffmpeg Lambda Layer build process shown in this repo: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer. The error shown is likely caused by the directory structure not matching what Lambda requires (see https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html for details). Also see https://medium.com/@adhorn/getting-started-with-aws-lambda-layers-for-python-6e10b1f9a5d.

Since this issue is not related to the code in this repo, I'll close here but please feel free to DM me on Twitter (@jbesw) if you have any other questions.
